const physicsQuestionBank = [
    { id: "p1", question: "A projectile is launched with velocity v at an angle θ with the horizontal. What is its total time of flight?", options: ["(2v sin θ) / g", "(v² sin 2θ) / g", "(v sin θ) / g", "(2v cos θ) / g"], answer: 0 },
    { id: "p2", question: "What are the dimensional formula dimensions of Planck's constant (h)?", options: ["[M L T⁻¹]", "[M L² T⁻¹]", "[M L² T⁻²]", "[M L T⁻²]"], answer: 1 },
    { id: "p3", question: "Acceleration due to gravity at a height h = R above Earth's surface is:", options: ["g / 2", "g / 3", "g / 4", "Zero"], answer: 2 },
    { id: "p4", question: "The work done by a conservative force along a closed path is always:", options: ["Positive", "Negative", "Zero", "Infinite"], answer: 2 },
    { id: "p5", question: "In an adiabatic process for an ideal gas, which quantity remains constant?", options: ["Temperature", "Pressure", "Entropy / Heat content", "Volume"], answer: 2 },
    { id: "p6", question: "What is the escape velocity from the surface of Earth of radius R?", options: ["√(gR)", "√(2gR)", "2√(gR)", "√(3gR)"], answer: 1 },
    { id: "p7", question: "Moment of inertia of a uniform thin rod of mass M and length L about an axis perpendicular to it and passing through its center is:", options: ["ML² / 12", "ML² / 3", "ML² / 2", "ML² / 6"], answer: 0 },
    { id: "p8", question: "If the length of a simple pendulum is quadrupled (4L), its time period becomes:", options: ["Doubled", "Halved", "Quadrupled", "Unchanged"], answer: 0 },
    { id: "p9", question: "The SI unit of magnetic flux is:", options: ["Tesla", "Weber", "Gauss", "Henry"], answer: 1 },
    { id: "p10", question: "The angle of dip at the magnetic equator of Earth is:", options: ["0°", "45°", "90°", "180°"], answer: 0 },
    { id: "p11", question: "The de Broglie wavelength λ of a particle of momentum p is given by:", options: ["λ = h / p", "λ = h p", "λ = p / h", "λ = h / p²"], answer: 0 },
    { id: "p12", question: "Bulk modulus of elasticity is defined as the ratio of:", options: ["Volumetric stress to volumetric strain", "Longitudinal stress to longitudinal strain", "Shearing stress to shearing strain", "Force to area"], answer: 0 },
    { id: "p13", question: "The fundamental frequency of an open organ pipe of length L and sound velocity v is:", options: ["v / (2L)", "v / (4L)", "2v / L", "v / L"], answer: 0 },
    { id: "p14", question: "The RMS speed of gas molecules of an ideal gas is proportional to:", options: ["T", "√T", "T²", "1 / √T"], answer: 1 },
    { id: "p15", question: "The ratio of specific heat capacities γ = Cp / Cv for a monoatomic gas is:", options: ["5/3", "7/5", "4/3", "9/7"], answer: 0 },
    { id: "p16", question: "When a dielectric slab of dielectric constant K is inserted completely into a parallel plate capacitor, its capacitance:", options: ["Increases by factor K", "Decreases by factor K", "Remains unchanged", "Becomes zero"], answer: 0 },
    { id: "p17", question: "Focal length of a convex lens immersed in a liquid of equal refractive index becomes:", options: ["Zero", "Infinite", "Half", "Double"], answer: 1 },
    { id: "p18", question: "Which logic gate gives an output of 1 only when all its inputs are 1?", options: ["AND", "OR", "NAND", "NOR"], answer: 0 },
    { id: "p19", question: "The SI unit of electric dipole moment is:", options: ["Coulomb-meter (C·m)", "Coulomb per meter", "Volt-meter", "Ampere-meter"], answer: 0 },
    { id: "p20", question: "The center of mass of a uniform semicircular ring of radius R from its center along the symmetry axis is located at:", options: ["2R / π", "4R / (3π)", "R / 2", "3R / (2π)"], answer: 0 },
    { id: "p21", question: "According to the Work-Energy Theorem, net work done on a body equals change in its:", options: ["Kinetic energy", "Potential energy", "Total mechanical energy", "Linear momentum"], answer: 0 },
    { id: "p22", question: "The phenomenon responsible for the primary rainbow in the sky is:", options: ["Refraction, dispersion, and total internal reflection", "Interference only", "Diffraction only", "Polarization only"], answer: 0 },
    { id: "p23", question: "The half-life T(1/2) of a radioactive substance with decay constant λ is:", options: ["0.693 / λ", "λ / 0.693", "1 / λ", "0.693 × λ"], answer: 0 },
    { id: "p24", question: "In a purely inductive AC circuit, the current lags behind the voltage by a phase angle of:", options: ["π / 2 (90°)", "π (180°)", "0°", "π / 4 (45°)"], answer: 0 },
    { id: "p25", question: "Self-inductance L of a solenoid of N turns is directly proportional to:", options: ["N²", "N", "1 / N", "√N"], answer: 0 }
];