const chemistryQuestionBank = [
    { id: "c1", question: "Which of the following compounds exhibits maximum hydrogen bonding?", options: ["H₂O", "H₂S", "NH₃", "HF"], answer: 0 },
    { id: "c2", question: "What is the oxidation state of Cr in potassium dichromate (K₂Cr₂O₇)?", options: ["+3", "+5", "+6", "+7"], answer: 2 },
    { id: "c3", question: "Which catalyst is used in the Haber process for ammonia synthesis?", options: ["V₂O₅", "Finely divided Fe with Mo", "Pt-Rh gauge", "Ni"], answer: 1 },
    { id: "c4", question: "The pH of a 10⁻⁸ M HCl aqueous solution at 25°C is closest to:", options: ["8.0", "6.98", "7.5", "6.0"], answer: 1 },
    { id: "c5", question: "Which gas is evolved when sodium bicarbonate reacts with acetic acid?", options: ["O₂", "H₂", "CO₂", "CO"], answer: 2 },
    { id: "c6", question: "What is the hybridization of carbon atoms in diamond?", options: ["sp³", "sp²", "sp", "dsp²"], answer: 0 },
    { id: "c7", question: "The IUPAC name of CH₃-CH₂-CHO is:", options: ["Propan-1-ol", "Propanal", "Propanone", "Propanoic acid"], answer: 1 },
    { id: "c8", question: "Radioactive decay follows which kinetics order?", options: ["Zero order", "First order", "Second order", "Third order"], answer: 1 },
    { id: "c9", question: "What is the geometry/shape of the SF₆ molecule?", options: ["Tetrahedral", "Octahedral", "Trigonal bipyramidal", "Square planar"], answer: 1 },
    { id: "c10", question: "Which element has the highest electronegativity on the Pauling scale?", options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"], answer: 2 },
    { id: "c11", question: "The ideal gas equation PV = nRT combines which gas laws?", options: ["Boyle's, Charles's, and Avogadro's laws", "Graham's and Dalton's laws", "Henry's law", "Raoult's law"], answer: 0 },
    { id: "c12", question: "The number of radial nodes in a 3p orbital is:", options: ["1", "2", "0", "3"], answer: 0 },
    { id: "c13", question: "Fehling's solution test is used to detect the presence of:", options: ["Aldehydes", "Ketones", "Ethers", "Aromatic esters"], answer: 0 },
    { id: "c14", question: "What is the bond order of the O₂ molecule?", options: ["1.0", "1.5", "2.0", "2.5"], answer: 2 },
    { id: "c15", question: "Which of the following oxide species is amphoteric in nature?", options: ["ZnO", "Na₂O", "SO₂", "CO₂"], answer: 0 },
    { id: "c16", question: "The monomer unit of natural rubber is:", options: ["Isoprene (2-methyl-1,3-butadiene)", "Neoprene", "Styrene", "Chloroprene"], answer: 0 },
    { id: "c17", question: "Permanent hardness of water is caused by the presence of soluble:", options: ["Chlorides and sulfates of Ca and Mg", "Bicarbonates of Ca and Mg", "Sodium carbonate", "Potassium nitrate"], answer: 0 },
    { id: "c18", question: "The average oxidation state of iron in magnetite (Fe₃O₄) is:", options: ["+8/3", "+2", "+3", "+4"], answer: 0 },
    { id: "c19", question: "Which halogen has the most negative (highest magnitude) electron gain enthalpy?", options: ["Fluorine", "Chlorine", "Bromine", "Iodine"], answer: 1 },
    { id: "c20", question: "Tyndall effect is characteristically exhibited by:", options: ["Colloidal solutions", "True solutions", "Pure solvents", "Ideal gases"], answer: 0 },
    { id: "c21", question: "The conjugate base of H₂SO₄ is:", options: ["HSO₄⁻", "SO₄²⁻", "H₃O⁺", "SO₃"], answer: 0 },
    { id: "c22", question: "The molecular geometry of XeF₄ according to VSEPR theory is:", options: ["Square planar", "Tetrahedral", "Octahedral", "See-saw"], answer: 0 },
    { id: "c23", question: "The coordination number of atoms in a Face-Centered Cubic (FCC) crystal lattice is:", options: ["6", "8", "12", "4"], answer: 2 },
    { id: "c24", question: "Lucas reagent (conc. HCl + anhyd. ZnCl₂) is used to distinguish between:", options: ["Primary, secondary, and tertiary alcohols", "Aldehydes and ketones", "Amines", "Carboxylic acids"], answer: 0 },
    { id: "c25", question: "Phenol gives a characteristic violet color upon reaction with neutral:", options: ["FeCl₃ solution", "AgNO₃ solution", "KMnO₄ solution", "Na₂CO₃ solution"], answer: 0 }
];