const mathsQuestionBank = [
    { id: "m1", question: "If A and B are square matrices of the same order such that AB = A and BA = B, then A² is equal to:", options: ["A", "B", "I", "0"], answer: 0 },
    { id: "m2", question: "The value of lim (x -> 0) [sin(x) / x] is equal to:", options: ["0", "1", "Infinity", "Undefined"], answer: 1 },
    { id: "m3", question: "What is the derivative of e^(x²) with respect to x?", options: ["e^(x²)", "2x e^(x²)", "x e^(x²)", "2 e^(x²)"], answer: 1 },
    { id: "m4", question: "The number of real solutions of the equation sin(x) = x is:", options: ["0", "1", "3", "Infinite"], answer: 1 },
    { id: "m5", question: "If the roots of quadratic equation ax² + bx + c = 0 are equal, then discriminant b² - 4ac is:", options: ["Greater than 0", "Equal to 0", "Less than 0", "Undefined"], answer: 1 },
    { id: "m6", question: "The value of complex number unit i⁴ (where i = √-1) is:", options: ["1", "-1", "i", "-i"], answer: 0 },
    { id: "m7", question: "The total number of subsets of a set containing n elements is:", options: ["2ⁿ", "n²", "2n", "n!"], answer: 0 },
    { id: "m8", question: "The value of combination ⁵C₂ is:", options: ["10", "20", "5", "12"], answer: 0 },
    { id: "m9", question: "The indefinite integral ∫ (1 / x) dx for x > 0 is equal to:", options: ["ln(x) + C", "-1 / x² + C", "x + C", "eˣ + C"], answer: 0 },
    { id: "m10", question: "Distance between the origin (0,0) and the point (3, 4) in the 2D plane is:", options: ["5", "7", "12", "25"], answer: 0 },
    { id: "m11", question: "The slope of the straight line given by equation 2x + 3y = 6 is:", options: ["-2/3", "2/3", "-3/2", "2"], answer: 0 },
    { id: "m12", question: "The exact trigonometric value of tan(45°) is:", options: ["1", "0", "1 / √2", "√3"], answer: 0 },
    { id: "m13", question: "Sum of the first n natural numbers 1 + 2 + 3 + ... + n is given by:", options: ["n(n + 1) / 2", "n²", "n(n - 1) / 2", "n(n + 1)(2n + 1) / 6"], answer: 0 },
    { id: "m14", question: "Determinant of 2x2 matrix [[1, 2], [3, 4]] is:", options: ["-2", "2", "10", "-10"], answer: 0 },
    { id: "m15", question: "Dot product of unit vectors i · j in 3D Cartesian coordinates is:", options: ["0", "1", "-1", "k"], answer: 0 },
    { id: "m16", question: "The modulus |z| of complex number z = 3 + 4i is:", options: ["5", "7", "25", "1"], answer: 0 },
    { id: "m17", question: "Equation of a circle centered at origin (0,0) with radius r is:", options: ["x² + y² = r²", "x + y = r", "x² - y² = r²", "xy = r²"], answer: 0 },
    { id: "m18", question: "The derivative of natural logarithmic function d/dx [ln(x)] is:", options: ["1 / x", "eˣ", "x", "1 / x²"], answer: 0 },
    { id: "m19", question: "The standard limit lim (x -> ∞) [1 + (1 / x)]ˣ equals:", options: ["e", "1", "0", "Infinity"], answer: 0 },
    { id: "m20", question: "The number of terms in the binomial expansion of (a + b)ⁿ is:", options: ["n + 1", "n", "n - 1", "2ⁿ"], answer: 0 },
    { id: "m21", question: "Arithmetic Mean (AM) of two numbers a and b is given by:", options: ["(a + b) / 2", "√(ab)", "2ab / (a + b)", "a - b"], answer: 0 },
    { id: "m22", question: "The eccentricity e of a circle is equal to:", options: ["0", "1", "Greater than 1", "Between 0 and 1"], answer: 0 },
    { id: "m23", question: "The indefinite integral ∫ cos(x) dx is equal to:", options: ["sin(x) + C", "-sin(x) + C", "tan(x) + C", "-cos(x) + C"], answer: 0 },
    { id: "m24", question: "The probability of getting a Head on a single toss of a unbiased fair coin is:", options: ["1/2", "1/4", "1", "0"], answer: 0 },
    { id: "m25", question: "The logarithm value log₁₀(100) is equal to:", options: ["2", "10", "1", "100"], answer: 0 }
];